# Generated by Django 4.2.3 on 2024-09-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_plantation', models.CharField(choices=[('SOY', 'Soy'), ('CORN', 'Corn'), ('TOBACCO', 'Tobacco'), ('RICE', 'Rice')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crops',
                'db_table': 'crop',
            },
        ),
    ]
