# Generated by Django 4.2.3 on 2024-09-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_plantation',
            field=models.CharField(choices=[('SOY', 'Soy'), ('CORN', 'Corn'), ('TOBACCO', 'Tobacco'), ('RICE', 'Rice')], max_length=30, unique=True),
        ),
    ]
