# Generated by Django 4.2.3 on 2024-09-08 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rural_producer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruralproducer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ruralproducer',
            name='state',
        ),
    ]
