# Generated by Django 4.2.3 on 2024-09-08 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rural_producer', '0002_remove_ruralproducer_city_remove_ruralproducer_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruralproducer',
            old_name='cpf',
            new_name='cpf_cnpj',
        ),
    ]
