# Generated by Django 4.2.3 on 2024-09-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rural_producer', '0003_rename_cpf_ruralproducer_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruralproducer',
            name='cpf_cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
