# Generated by Django 4.2.3 on 2024-09-09 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_farm_city_farm_state'),
        ('rural_producer', '0004_alter_ruralproducer_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruralproducer',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.farm'),
        ),
    ]
