# Generated by Django 4.2.3 on 2024-09-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='plantable_area',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
